name: Update Profile README

on:
  push:
    branches:
      - main # Or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rich uv

      - name: Run Makefile
        run: make update

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of profile README"
          push_options: "--force-with-lease" # Recommended to prevent overwriting remote changes